/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef FORTUMO_AUTODEFS_H
#define FORTUMO_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_FORTUMO_NAME "Fortumo"
#define S3E_EXT_FORTUMO_HASH 0xbab0f5b1

#endif /* !FORTUMO_AUTODEFS_H */
