/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "Fortumo_autodefs.h"
#include "s3eEdk.h"
#include "Fortumo.h"
//Declarations of Init and Term functions
extern s3eResult FortumoInit();
extern void FortumoTerminate();


s3eResult FortumoRegister(FortumoCallback cbid, s3eCallback fn, void* pData)
{
    return s3eEdkCallbacksRegister(S3E_EXT_FORTUMO_HASH, FORTUMO_CALLBACK_MAX, cbid, fn, pData, 0);
};

s3eResult FortumoUnRegister(FortumoCallback cbid, s3eCallback fn)
{
    return s3eEdkCallbacksUnRegister(S3E_EXT_FORTUMO_HASH, FORTUMO_CALLBACK_MAX, cbid, fn);
}

void FortumoRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[5];
    funcPtrs[0] = (void*)FortumoRegister;
    funcPtrs[1] = (void*)FortumoUnRegister;
    funcPtrs[2] = (void*)FortumoRequestPayment;
    funcPtrs[3] = (void*)FortumoTerminate;
    funcPtrs[4] = (void*)FortumoInit;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[5] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("Fortumo", funcPtrs, sizeof(funcPtrs), flags, FortumoInit, FortumoTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int FortumoStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&FortumoRegisterExt;
    return 0;
}

int g_FortumoVal = FortumoStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    FortumoRegisterExt();
}
#endif

#endif
